handlers:
  create_new_release:
    active: true
    assignees:
      - taltrui
    labels:
      - ReleaseTEST
  mergeable:
    version: 2
    active: true
  cleanup_release:
    active: true
  is_semantic:
    active: true
  notify_and_clean_released:
    active: true
    notify: false
    clean: true
  notify_merge_to_release:
    active: true
  level_with_master:
    active: true
  complete_new_pr:
    active: true
  completition_metrics:
    active: true
    config:
      sheet_id: 1_ccV3CAHd0T5f2Ys9tOWe7fjO8YpfRHorPs-7CoQKyI
  assigner:
    active: true
    config:
      assignees:
        - taltrui
        - glipina
        - segulino
  
  
